# Generated by Django 4.1.5 on 2023-03-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_receptonist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_receptonist',
        ),
    ]
