# Generated by Django 4.1.5 on 2023-02-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciption', '0010_sortleave_late_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SortLeave',
        ),
    ]
