# Generated by Django 4.1.5 on 2023-02-19 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authority', '0010_leaveapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('dadeline', models.DateField()),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('task_message', models.TextField()),
                ('completion_report', models.TextField()),
                ('completion_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned', to=settings.AUTH_USER_MODEL)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('feedback_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_by', to=settings.AUTH_USER_MODEL)),
                ('feedback_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_back', to='authority.task')),
            ],
        ),
    ]
