# Generated by Django 4.1.5 on 2023-02-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0011_task_taskfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='taskfeedback',
            name='feedback_heading',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
