# Generated by Django 4.1.5 on 2023-02-19 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authority', '0012_task_completion_date_taskfeedback_feedback_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_report',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_message',
            field=models.TextField(null=True),
        ),
    ]
