# Generated by Django 4.1.5 on 2023-02-20 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authority', '0013_alter_task_assigned_to_alter_task_completion_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completion_report',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completion_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_message',
        ),
        migrations.CreateModel(
            name='TaskAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_message', models.TextField(null=True)),
                ('completion_report', models.TextField(null=True)),
                ('completion_status', models.BooleanField(default=False)),
                ('completion_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('task_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_task', to='authority.task')),
            ],
        ),
        migrations.AlterField(
            model_name='taskfeedback',
            name='feedback_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_back', to='authority.taskassigned'),
        ),
    ]
