# Generated by Django 4.1.5 on 2023-02-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0014_remove_task_assigned_to_remove_task_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigned',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
