# Generated by Django 4.1.5 on 2023-02-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0015_alter_taskassigned_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dadeline',
            new_name='deadline',
        ),
    ]
