# Generated by Django 4.1.5 on 2023-03-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0019_latepresentandleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyHolyDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=50)),
                ('holyday_month', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=10)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
