# Generated by Django 4.1.5 on 2023-03-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0020_monthlyholyday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyHolyDay',
            new_name='MonthlyHoliDay',
        ),
    ]
