# Generated by Django 4.1.5 on 2023-03-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0022_rename_holyday_month_monthlyholiday_holiday_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyholiday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
