# Generated by Django 4.1.5 on 2023-03-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0025_leaveapplication_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='officetime',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
