# Generated by Django 4.1.5 on 2023-03-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0027_alter_officetime_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officetime',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
