# Generated by Django 4.1.5 on 2023-03-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employeesalary_basic_salary'),
        ('authority', '0028_alter_officetime_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='latepresentandleave',
            name='over_time_bonus',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('entering_time', models.TimeField(null=True)),
                ('exit_time', models.TimeField(null=True)),
                ('late_present', models.DurationField(blank=True, null=True)),
                ('over_time', models.DurationField(blank=True, null=True)),
                ('attendance_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='employee.employeeinfo')),
            ],
        ),
    ]
