# Generated by Django 4.1.5 on 2023-03-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0029_latepresentandleave_over_time_bonus_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
