# Generated by Django 4.1.5 on 2023-03-17 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0008_alter_employeesalary_basic_salary'),
        ('authority', '0030_attendance_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollmonth',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='Jan', max_length=10),
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_conveyance', models.FloatField()),
                ('total_food_allowance', models.FloatField()),
                ('total_medical_allowance', models.FloatField()),
                ('total_house_rent', models.FloatField()),
                ('total_mobile_allowance', models.FloatField()),
                ('total_bonus', models.FloatField(default=0.0)),
                ('late_present_diduct', models.FloatField(default=0.0)),
                ('extra_leave_diduct', models.FloatField(default=0.0)),
                ('total_diduct', models.FloatField(null=True)),
                ('total_salary', models.FloatField(null=True)),
                ('total_absence', models.IntegerField(null=True)),
                ('extra_late_present', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('festival_bonus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festival_bonus', to='authority.festivalbonus')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepared_by', to=settings.AUTH_USER_MODEL)),
                ('salary_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_employee', to='employee.employeeinfo')),
                ('salary_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_month', to='authority.payrollmonth')),
                ('salary_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_salary', to='employee.employeesalary')),
            ],
        ),
    ]
