# Generated by Django 4.1.5 on 2023-03-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0032_payrollmonth_total_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='total_overtime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='total_overtime_bonus',
            field=models.FloatField(default=0),
        ),
    ]
