# Generated by Django 4.1.5 on 2023-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0033_monthlysalary_total_overtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmonth',
            name='totla_offdays',
            field=models.IntegerField(default=0),
        ),
    ]
